-- 0001_schema_isolado_reconstruido.sql  (C27R9 · 28/set/2026)
-- ESCOPO: SOMENTE AMBIENTE ISOLADO. NUNCA aplicar em producao.
-- ORIGEM: DDL RECONSTRUIDO a partir do USO no api.py v7.77 (colunas lidas/escritas
-- pelo percurso vitrine -> backtest -> registro -> /mt5/enviar -> job -> snapshot).
-- NAO e o DDL de producao (esse so existe no banco de producao; Passo 0 pendente).
-- Guard: recusa rodar num banco sem a sentinela de isolamento criada logo abaixo
-- na primeira aplicacao (banco vazio) -- em banco com tabelas e sem sentinela, aborta.
DO $$
BEGIN
  IF to_regclass('public._bt_homolog_marker') IS NULL
     AND to_regclass('public.conector_bots') IS NOT NULL THEN
    RAISE EXCEPTION 'ABORTADO: banco com conector_bots e sem _bt_homolog_marker (parece producao)';
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public._bt_homolog_marker (
  id int PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  ambiente text NOT NULL DEFAULT 'isolado-local',
  criado_em timestamptz NOT NULL DEFAULT now());
INSERT INTO public._bt_homolog_marker(id) VALUES (1) ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS public.perfis (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email text, nome text,
  plano text NOT NULL DEFAULT 'free',
  plano_valido_ate timestamptz,
  stripe_customer_id text, stripe_subscription_id text,
  free_tests_usados int NOT NULL DEFAULT 0,
  backtests_limite int,
  idioma text DEFAULT 'pt',
  motivo text, ts timestamptz,
  criado_em timestamptz NOT NULL DEFAULT now());

CREATE OR REPLACE FUNCTION public._bt_perfil_novo() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  INSERT INTO public.perfis(id, email) VALUES (NEW.id, NEW.email)
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS trg_bt_perfil_novo ON auth.users;
CREATE TRIGGER trg_bt_perfil_novo AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public._bt_perfil_novo();

CREATE TABLE IF NOT EXISTS public.conector_bots (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  bot_token text NOT NULL UNIQUE,
  nome text, simbolo text, magic_number bigint,
  config_operacional jsonb,
  mq5_codigo text, mq5_filename text,
  excluido boolean NOT NULL DEFAULT false,
  ultimo_ping timestamptz, posicoes_abertas int,
  ultimo_equity double precision, ultimo_dd double precision,
  ultima_direcao text, ultimo_padrao text,
  conector_visto_em timestamptz, conector_parado_em timestamptz,
  subir_pedido_em timestamptz,
  criado_em timestamptz NOT NULL DEFAULT now());

CREATE TABLE IF NOT EXISTS public.mt5_jobs (
  job_id text PRIMARY KEY,
  bot_token text, filename text, magic bigint, mq5 text,
  status text, aprovado boolean, log text,
  gen_hash text, pre_validado boolean,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now());

CREATE TABLE IF NOT EXISTS public.mq5_cache (
  gen_hash text PRIMARY KEY, mq5 text, aprovado boolean DEFAULT false,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now());

CREATE TABLE IF NOT EXISTS public.conector_snapshots (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid, bot_token text, conta_login text, corretora text,
  simbolo text, magic_number bigint,
  equity double precision, balance double precision, margem_livre double precision,
  posicoes_abertas int, lucro_flutuante double precision, drawdown_atual double precision,
  direcao_d1 text, padrao_ativo text, detalhe_json jsonb,
  criado_em timestamptz NOT NULL DEFAULT now());

CREATE TABLE IF NOT EXISTS public.backtests_historico (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid, sessao_id text, ativo text, periodo text, timeframe text,
  estrategia_nome text, ema_period int, stop_loss double precision,
  take_profit double precision, capital double precision, comissao double precision,
  max_ops int, retorno double precision, win_rate double precision,
  profit_factor double precision, sharpe double precision, max_drawdown double precision,
  total_trades int, parametros jsonb, codigo_hash text, permite_treino boolean,
  criado_em timestamptz NOT NULL DEFAULT now());

CREATE TABLE IF NOT EXISTS public.estudo_biblioteca (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  estrategia_id text, estrategia_nome text, ativo text, periodo text, timeframe text,
  retorno double precision, win_rate double precision, profit_factor double precision,
  sharpe double precision, trades int, forca double precision, captura_pct double precision,
  regras_versao text, medido_em timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS public.estudo_biblioteca_v2 (LIKE public.estudo_biblioteca INCLUDING ALL);

CREATE TABLE IF NOT EXISTS public.agente_sugestoes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid, regra text, lida boolean DEFAULT false, titulo text, mensagem text,
  detalhe_json jsonb, bot_token text, bot_nome text, nivel text,
  criado_em timestamptz NOT NULL DEFAULT now());

CREATE TABLE IF NOT EXISTS public.agente_eventos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid, bot_token text, bot_nome text, tipo text, regra text, simbolo text,
  lado text, preco double precision, motivo text, mensagem text, detalhe_json jsonb,
  criado_em timestamptz NOT NULL DEFAULT now());

CREATE TABLE IF NOT EXISTS public.mt5_comandos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bot_id bigint REFERENCES public.conector_bots(id) ON DELETE CASCADE,
  bot_token text, user_id uuid, tipo text NOT NULL, params jsonb DEFAULT '{}'::jsonb,
  status text NOT NULL DEFAULT 'pendente', origem text, resultado jsonb,
  expira_em timestamptz, entregue_em timestamptz, confirmado_em timestamptz,
  criado_em timestamptz NOT NULL DEFAULT now());

CREATE TABLE IF NOT EXISTS public.babymachine_operacoes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid, bot_id bigint, bot_nome text, ativo text, timeframe text, fonte text,
  status text, decisao jsonb, detalhe_ea jsonb, resultado jsonb,
  ts_criada timestamptz, ts_entrada timestamptz, ts_saida timestamptz,
  evento_id_fechou bigint, created_at timestamptz NOT NULL DEFAULT now());

CREATE TABLE IF NOT EXISTS public.radar_analises_cache (
  chave text PRIMARY KEY, mensagens jsonb, criado_em timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.codigos_acesso (
  codigo text PRIMARY KEY, usado_por uuid, usado_em timestamptz, plano text, dias int);
CREATE TABLE IF NOT EXISTS public.calendario_economico (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, data_evento timestamptz,
  moeda text, impacto text, titulo text, actual text, forecast text, previous text);
CREATE TABLE IF NOT EXISTS public.radar_chat_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id uuid, ativo text,
  estrategia_id text, idioma text, plano text, pergunta text, resposta text,
  config jsonb, resultado jsonb, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.radar_chat_uso (
  user_id uuid, semana text, usados int DEFAULT 0, PRIMARY KEY (user_id, semana));

-- RPCs zero-arg que a api chama (manutencao)
CREATE OR REPLACE FUNCTION public._bm_operacoes_limpar_antigas() RETURNS void
LANGUAGE sql AS $$ SELECT 1 $$;
CREATE OR REPLACE FUNCTION public._mt5_expirar_comandos() RETURNS void
LANGUAGE sql AS $$
  UPDATE public.mt5_comandos SET status='expirado'
   WHERE status='pendente' AND expira_em IS NOT NULL AND expira_em < now() $$;

-- RLS: o front (anon key + JWT do usuario) so le o proprio perfil e os proprios bots;
-- todo o resto e service_role (api). Default deny.
DO $$ DECLARE t text; BEGIN
  FOR t IN SELECT tablename FROM pg_tables WHERE schemaname='public' LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('GRANT ALL ON public.%I TO service_role', t);
  END LOOP; END $$;
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;
GRANT SELECT ON public.perfis, public.conector_bots TO authenticated;
DROP POLICY IF EXISTS perfis_proprio ON public.perfis;
CREATE POLICY perfis_proprio ON public.perfis FOR SELECT TO authenticated USING (id = auth.uid());
DROP POLICY IF EXISTS bots_proprios ON public.conector_bots;
CREATE POLICY bots_proprios ON public.conector_bots FOR SELECT TO authenticated USING (user_id = auth.uid());
